puts "Hello World!"
puts ""
puts "Sou Vitória, programadora iniciante e discípula QA na Compass.Uol há pouco mais de um mês."
puts "Estou no 3° período de Sistemas de Informação na Faculdade Uninassau."
puts "Este é o meu primeiro 'código' usando Ruby, nada muito sofisticado, mas um ótimo começo para uma leiga."
puts "Espero com o tempo pegar a prática e me desenvolver como uma excelente profissional de TI."
puts "Até breve!"
puts ""
puts "Bye!"