puts "Tipos de Dados"
puts ""
puts "Assim como em outras tantas linguagens, o Ruby tem tipos de dados."
puts "Esses tipos são importantes para a facilitação da manipulação dos dados pela linguagem."
puts "Segue os tipos mais usuais:"
puts ""
puts "Integer: trabalha com os inteiros positivos, negativos e com o 0(zero);"
puts ""
puts "Float: trabalha com os decimais, com pontos flutuantes;"
puts ""
puts "Boolean: trabalha com duas possibilidades -> true ou false;"
puts ""
puts "String: trabalha com os conjuntos de caracteres que formam textos;"
puts ""
puts "Array: é um tipo mais complexo de dado, comumente conhecido por armazenar listas ordenadas;"
puts ""
puts "Symbol: outro tipo complexo que trabalha como string, mas com objeto imutável;"
puts ""
puts "Hash: trabalha com coleção de dados organizados por chaves únicas e seus respectivos valores."
puts "A diferença dele para o Array é no uso de chaves({}) no lugar de colchetes([]);"
puts ""
puts "Bye!"